CHANGELOG.md, package.json, src/__tests__/mocks/notifications/subscription-activated.mock.ts, src/__tests__/mocks/notifications/subscription-canceled.mock.ts, src/__tests__/mocks/notifications/subscription-created.mock.ts, src/__tests__/mocks/notifications/subscription-imported.mock.ts, src/__tests__/mocks/notifications/subscription-past-due.mock.ts, src/__tests__/mocks/notifications/subscription-paused.mock.ts, src/__tests__/mocks/notifications/subscription-resumed.mock.ts, src/__tests__/mocks/notifications/subscription-trialing.mock.ts, src/__tests__/mocks/notifications/subscription-updated.mock.ts, src/__tests__/resources/transactions.test.ts, src/entities/shared/transaction-payment-attempt.ts, src/entities/subscription/subscription-notification.ts, src/entities/transaction/transaction-includes.ts, src/resources/customers/operations/list-customer-query-parameters.ts, src/resources/subscriptions/operations/resume-subscription-request-object.ts, src/resources/transactions/index.ts, src/resources/transactions/operations/index.ts, src/resources/transactions/operations/update-transaction-query-parameters.ts, src/types/shared/transaction-payment-attempt-response.ts, src/types/subscription/subscription-notification-response.ts, src/types/transaction/transaction-response.ts
- Added `availablePaymentMethods` as an `include` Parameter to all transaction operations.
- Added `importMeta` to Subscription webhooks.
- Filter customers by email address in `customers.list()` operation, see [related changelog](https://developer.paddle.com/changelog/2024/filter-customers-email?utm_source=dx&utm_medium=paddle-node-sdk).
- New payment method ID field for transaction payments, see [related changelog](https://developer.paddle.com/changelog/2024/payment-method-paddle-id?utm_source=dx&utm_medium=paddle-node-sdk).
- Fixed `effective_from` enum in Resume subscription operations.
- Deprecated `storedPaymentMethodId` from transaction payments in favour of `paymentMethodId` field.
---
=> Adding latest API changes

CHANGELOG.md, README.md, jest.config.js, package.json, src/__tests__/mocks/notifications/address-created.mock.ts, src/__tests__/mocks/notifications/address-imported.mock.ts, src/__tests__/mocks/notifications/address-updated.mock.ts, src/__tests__/mocks/notifications/business-created.mock.ts, src/__tests__/mocks/notifications/business-imported.mock.ts, src/__tests__/mocks/notifications/business-updated.mock.ts, src/__tests__/mocks/resources/addresses.mock.ts, src/__tests__/mocks/resources/businesses.mock.ts, src/entities/address/address.ts, src/entities/business/business.ts, src/index.ts, src/internal/index.ts, src/internal/types/config.ts, src/notifications/entities/address/address-notification.ts, src/notifications/entities/business/business-notification.ts, src/notifications/types/address/address-notification-response.ts, src/notifications/types/business/business-notification-response.ts, src/types/address/address-response.ts, src/types/business/business-response.ts
- Exported `ApiError` class for usage in `try/catch` block.
- Added `customerId` property to `Address` and `Business` entities.
---
Fixes: #7
=> Added customerId to address and business entities

CHANGELOG.md, package.json, src/enums/shared/error-code.ts
- Updated `ErrorCode` enum in `TransactionPaymentAttempt` to include a new error code `declined_not_retryable`
---
=> Updated `ErrorCode` enum in `TransactionPaymentAttempt` to include a new error code `declined_not_retryable`

CHANGELOG.md, package.json, src/entities/price/price.ts, src/notifications/entities/price/price-notification.ts, src/notifications/types/price/price-notification-response.ts, src/types/price/price-response.ts
- Handled missing `unitPriceOverrides` in the `subscriptions.getPaymentMethodChangeTransaction` operation.
---
Fixes: #18
=> Handled missing `unitPriceOverrides` in the `subscriptions.getPaymentMethodChangeTransaction` operation.

CHANGELOG.md, package.json, src/__tests__/mocks/resources/pricing-preview.mock.ts, src/entities/pricing-preview/pricing-preview.ts, src/types/pricing-preview/pricing-preview-response.ts
- Updated the optional properties returned by `pricingPreview.preview` operation to match the API response.
---
=> Updated the optional properties in Pricing preview

CHANGELOG.md, README.md, package.json, src/__tests__/internal/logger.test.ts, src/index.ts, src/internal/api/client.ts, src/internal/api/index.ts, src/internal/api/log-level.ts, src/internal/base/logger.ts, src/internal/types/config.ts, src/paddle.ts
- Added a new option to change the logging level of the SDK. You can now set the logging level to `verbose`, `warn`, `error` or `none`. The default logging level is `verbose`.
---
Fixes: #8
=> feat(logs): Added an option to control log level

CHANGELOG.md, package.json, src/entities/shared/transaction-payment-attempt.ts, src/types/shared/transaction-payment-attempt-response.ts
- Marked `paymentMethodId` as nullable in `TransactionPaymentAttempt` as it can be `null`.
---
=> fix(Transaction): Marked `paymentMethodId` as nullable

CHANGELOG.md, package.json, src/__tests__/mocks/resources/notification-settings.mock.ts, src/entities/notification-settings/notification-settings.ts, src/enums/notification-settings/traffic-source.ts, src/resources/notification-settings/operations/create-notification-settings-request-body.ts, src/resources/notification-settings/operations/list-notification-settings-query-parameters.ts, src/resources/notification-settings/operations/update-notification-settings-request-body.ts, src/types/notification-settings/notification-settings-response.ts
Adds the `trafficSource` types to notification settings for create, update and list
Usage:
```
const ntfSet = await paddle.notificationSettings.create({
description: "Test Notification Setting",
destination: "https://your.app/webhook",
subscribedEvents: ["address.created"],
type: "url",
trafficSource: "simulation",
});
```
=> feat(NotificationSetting): Add trafficSource field

CHANGELOG.md, package.json, src/__tests__/mocks/notifications/subscription-activated.mock.ts, src/__tests__/mocks/notifications/subscription-canceled.mock.ts, src/__tests__/mocks/notifications/subscription-imported.mock.ts, src/__tests__/mocks/notifications/subscription-past-due.mock.ts, src/__tests__/mocks/notifications/subscription-paused.mock.ts, src/__tests__/mocks/notifications/subscription-resumed.mock.ts, src/__tests__/mocks/notifications/subscription-trialing.mock.ts, src/__tests__/mocks/notifications/subscription-updated.mock.ts, src/notifications/entities/subscription/index.ts, src/notifications/entities/subscription/subscription-created-notification.ts, src/notifications/entities/subscription/subscription-notification.ts, src/notifications/events/subscription/subscription-activated-event.ts, src/notifications/events/subscription/subscription-canceled-event.ts, src/notifications/events/subscription/subscription-created-event.ts, src/notifications/events/subscription/subscription-imported-event.ts, src/notifications/events/subscription/subscription-past-due-event.ts, src/notifications/events/subscription/subscription-paused-event.ts, src/notifications/events/subscription/subscription-resumed-event.ts, src/notifications/events/subscription/subscription-trialing-event.ts, src/notifications/events/subscription/subscription-updated-event.ts, src/notifications/types/subscription/index.ts, src/notifications/types/subscription/subscription-created-notification-response.ts, src/types/events/events-response.ts
Updates the `transactionId` for `SubscriptionNotification` to be non-nullable, the field is still omitted from all notifications other than subscription created
=> fix(SubscriptionNotification): mark transactionId as non-null

CHANGELOG.md, package.json
Release v2 as a stable release
- https://github.com/PaddleHQ/paddle-node-sdk/pull/45
- https://github.com/PaddleHQ/paddle-node-sdk/pull/69
=> chore: bump version to v2 stable

CHANGELOG.md, package.json, src/resources/customer-portal-sessions/index.ts
Related to issue: https://github.com/PaddleHQ/paddle-node-sdk/issues/76
With the 2.0.0 release to support the additional runtimes, the `.js` extension needs to be added to all imports
=> fix: update customer portal sessions imports

.eslintrc.yml, CHANGELOG.md, package.json, src/resources/payment-methods/index.ts
Related to the following issue - https://github.com/PaddleHQ/paddle-node-sdk/issues/76
Adds the `eslint-plugin-import` rule to ensure that all imports and exports include the `.js` extension
=> chore: add eslint file extension rule

CHANGELOG.md, package.json, src/__tests__/mocks/notifications/invoice-paid.mock.ts, src/__tests__/notifications/notifications-parser.test.ts, src/entities/events/event-collection.ts, src/entities/notifications/notification.ts, src/internal/base/index.ts, src/internal/base/transform.ts, src/notifications/events/generic/generic-event.ts, src/notifications/events/generic/index.ts, src/notifications/events/index.ts, src/notifications/helpers/webhooks.ts
Related to issue: https://github.com/PaddleHQ/paddle-node-sdk/issues/80
There are some webhook events that are no longer supported but there is still a use for them, some of the other SDKs have the concept of a generic event which is not explicitly handled or typed, this PR also introduces a `GenericEvent` which will not have any typing so it will be on the implementation to ignore or cast the types.
The recommended usage for this will be to handle the webhook as you would anything else but intervene with any ts suggestions i.e.
```
switch (event?.eventType) {
case EventName.SubscriptionCreated:
// handle subscribtion created event
// @ts-ignore
case "invoice.paid":
// handle invoice paid event as a generic event
```
> To follow inline with the rest of the webhook events, the keys of the …
=> Support unknown webhook events

CHANGELOG.md, package.json, src/__tests__/mocks/resources/transactions.mock.ts, src/entities/subscription/transaction-line-item-preview.ts, src/types/shared/transaction-line-item-preview-response.ts
Related docs: https://developer.paddle.com/api-reference/transactions/preview-transaction
Adds `proration` to `details.lineItems` for transaction previews
=> Add proration to transaction preview line items

CHANGELOG.md, package.json, src/__tests__/mocks/resources/subscriptions.mock.ts, src/entities/subscription/subscription-discount.ts, src/types/subscription/subscription-discount-response.ts
Related docs: https://developer.paddle.com/api-reference/subscriptions/overview
Subscription `discount.startsAt` can now be null
=> Subscription discount can now be null

README.md
Updates the webhook example to use async/await since `paddle.webhooks.unmarshal` returns a promise the previous example wouldn't work, the other possible option instead of async/await is to use:
```
paddle.webhooks.unmarshal(rawRequestBody, secretKey, signature).then((eventData) => {
switch (eventData.eventType) { ...
```
=> docs: update webhook example to use async/await

README.md
First time using Paddle and noticed the documentation was still using string literals ('verbose', 'error') for log levels instead of the LogLevel enum. Here's a small PR to update the example in the docs to prevent confusion for new users like myself. Hope it's okay to contribute directly!
Updates the usage example to use the `LogLevel` enum instead of the `'verbose'` or `'error'` string literals:
``` typescript
import { Environment, LogLevel, Paddle } from '@paddle/paddle-node-sdk'
const paddle = new Paddle('API_KEY')
```
```typescript
const paddle = new Paddle('API_KEY', {
environment: Environment.production, // or Environment.sandbox for accessing sandbox API
logLevel: LogLevel.verbose // or LogLevel.error for less verbose logging
})
```
=> docs: update usage example to use LogLevel

.github/workflows/publish.yml
Check if the version in package.json has already been published to skip the publish step
Uses [npm view](https://docs.npmjs.com/cli/v8/commands/npm-view) to check for the version in all releases, I've gone with this approach instead of comparing against the latest released version as we still use `rc` and `beta` releases this could still cause some issues with missing those
This will result in a command like `npm view @paddle/paddle-node-sdk@2.5.0 version` which will either return the version `2.5.0` or an error
```
npm error code E404
npm error 404 No match found for version 2.5.1
npm error 404
npm error 404  '@paddle/paddle-node-sdk@2.5.1' is not in this registry.
```
Partial solution from https://stackoverflow.com/questions/58804498/only-npm-publish-when-version-changes-in-tfs-build
=> ci: skip publish if version already exists

package.json
Related to issue: https://github.com/PaddleHQ/paddle-node-sdk/issues/117
Includes additional exports for non-node environments, allowing the runtime to pick up the `edge` build, which has a replacement implementation for `node:crypto` unavailable in other runtimes.
As we've seen a couple issue with `@paddle/paddle-node-sdk` and nextjs on cloudflare, here is a usage guide:
Import the `Paddle` class from `@paddle/paddle-node-sdk` in the API route and create the instance in the route handler
```typescript
// app/api/webhook/route.ts
export const runtime = "edge";
import {
Environment,
LogLevel,
Paddle,
PaddleOptions,
} from "@paddle/paddle-node-sdk";
import { NextRequest } from "next/server";
const paddleOptions: PaddleOptions = {
environment:
(process.env.NEXT_PUBLIC_PADDLE_ENV as …
```
=> fix: include exports for non-node environments

.github/workflows/build-test.yml, .github/workflows/linting.yml, .github/workflows/publish.yml, .github/workflows/release-on-push.yml
Pin the github actions to specific commits.
This is considered good practice, in particular due to recent concerns over compromised actions
=> Pin github actions to commits

CHANGELOG.md, package.json, src/resources/subscriptions/index.ts
Related issue: https://github.com/PaddleHQ/paddle-node-sdk/issues/132
Updates the `requestBody` in `subscription.cancel` to be optional
Before:
```
await paddle.subscription.cancel(subscriptionId, {})
```
After:
```
await paddle.subscription.cancel(subscriptionId)
```
=> feat: make the subscription cancel request body optional

.github/dependabot.yml, CHANGELOG.md, package.json
- Added PR labels to dependabot config.
- Dependabot updates
- Fixed a typo `paddle.businesses.archive` operation.
---
=> chore: update dependabot labels and bump version to 2.7.3

CHANGELOG.md, package.json
- Updated package version to `2.8.0`
- Updated changelog with all the changes in this version
=> chore: bump version to 2.8.0 and update CHANGELOG

.github/workflows/build-test.yml, .github/workflows/linting.yml, .github/workflows/publish.yml, .github/workflows/release-on-push.yml, CHANGELOG.md, UPGRADING.md, package.json, src/internal/api/client.ts, src/paddle.ts, tsconfig.base.json
> **Breaking changes:** This version includes major improvements that introduce breaking changes. These are called out
> below.
- **Breaking change:** Updated the minimum required Node.js version to v20.
- **Breaking change:** Changed default logging level to `error`. You can change it to `verbose` or `none` in the
SDK configuration.
- Changed the typescript configuration to transpile into ES2022
---
Fixes: #139
=> feat!: Upgrade minimum node version to 20

CHANGELOG.md, package.json
- Added support for new payment methods `blik`, `mb_way`, `pix` and `upi`. See [related changelog](https://developer.paddle.com/changelog/2025/blik-mbway-payment-methods?utm_source=dx&utm_medium=paddle-node-sdk).
- Non-catalog discounts on Transactions, see [changelog](https://developer.paddle.com/changelog/2025/custom-discounts?utm_source=dx&utm_medium=paddle-node-sdk)
- Support `retained_fee` field on totals objects to show the fees retained by Paddle for the adjustment.
- `ApiError` will now have `retryAfter` property set for [too_many_requests](https://developer.paddle.com/errors/shared/too_many_requests) errors
- `PricingPreview`, `PricingPreviewDiscounts`, `PricingPreviewDetails`, `PricingPreviewLineItem` types are now exported
=> docs(release): v3.3.0
